'use strict';
/* POST {id, token, theme, honoree:{names[],age}, facts:[...]}
 * -> {questions[12], spares[], cards[20], event} generated by Claude (server-side only).
 * Rate limit: generations per event come from site.config.json (free 1, pass 3). */
const { handler, readJson, send, httpError } = require('./_lib/http');
const { getDb } = require('./_lib/db');
const E = require('./_lib/events');
const { generateDeck, getClient } = require('./_lib/ai');

module.exports = handler(['POST'], async (req, res) => {
  const body = await readJson(req);
  const db = getDb();
  const ev = await E.requireHost(body.id, body.token, db);
  const client = getClient();
  if (!client) throw httpError(503, 'AI personalisation is not configured yet.', 'ai_unconfigured');
  const theme = E.THEMES.includes(body.theme) ? body.theme : ev.theme;

  await E.reserveGeneration(ev.id, db); // throws 429 when the allowance is used up
  const t0 = Date.now();
  try {
    const deck = await generateDeck({ theme, honoree: E.cleanHonoree(body.honoree || ev.honoree || {}), facts: body.facts }, {
      client, log: (m) => console.log(`[generate-deck ${ev.id}] ${m}`),
    });
    for (const u of deck.usage) await E.recordAiCost(ev.id, { ...u, ok: true, ms: Date.now() - t0 }, db);
    console.log(`[generate-deck ${ev.id}] ok attempts=${deck.attempts} cost=$${deck.costUsd.toFixed(4)} tokens=${deck.usage.map((u) => `${u.model}:${u.input_tokens}/${u.output_tokens}`).join(',')}`);
    const { usage, ...out } = deck;
    return send(res, 200, { ...out, event: E.publicEvent(await db.get('events', ev.id)) });
  } catch (e) {
    await E.refundGeneration(ev.id, db); // failed generations don't count against the allowance
    for (const u of e.usage || []) await E.recordAiCost(ev.id, { ...u, ok: false }, db);
    console.error(`[generate-deck ${ev.id}] failed: ${e.message}`);
    throw e.status ? e : httpError(502, 'The AI service had a problem. Please try again.');
  }
});
